### ISSUE TITLE
Add telemetry support for H8 3D

### ISSUE THREAD

**Issue by C0br4** [silver13/H8_3D#1]
I am so used to the great Telemetry support in the other Silverware versions that its a shame the unique H8 3D doesn't have it. Maybe one day all the silverware versions could even share a single codebase with different build targets to accommodate the different supported boards. Thanks for making crappy plastic toys to insane precise micro racers

**Comment by silver13** [comment]
The single codebase could be nice, but I like make sure the quad flies with the posted code, as this is intended for uses without programming experience. Sometimes little things can break hardware support, especially as the hardware is sometimes different between quads in various ways.

I would probably do things differently now but when I started this I didn't know how it's going to work out.

Anyway, I added telemetry now, I didn't think anyone uses h8 3ds because it was never really popular.

**Comment by C0br4** [comment]
Great to hear! Sadly I lost my H83D due to missing telemetry ;) and running the lipo flat but as soon as a new one arrives I will test the changes.
